---
title: "Mendelian Randomization analysis of DeepSEA generated data"
output: html_notebook
---

```{r}

library(MendelianRandomization)
library(dplyr)
library(meta)
library(knitr)
library(kableExtra)
library(tidyverse)
```

```{r}
files <- list.files(path="../../dat/res/", "*.csv")

result <- matrix(ncol=5, nrow=length(files))

for (i in 1:length(files)) {
  f <- files[i]
  # print(f)
  #
  seq_predictions = read.csv(file.path("../../dat/res/", f))
  # # do.call(cbind, lapply(x, is.nan))

  seq_predictions[is.nan(seq_predictions)] <- 0
  seq_predictions <- seq_predictions %>%
    filter(
      X_pred_var > 0 & Y_pred_var > 0
    )

  ivw_vals = list()
  egger_vals = list()

  egger_result <- matrix(ncol=6, nrow=25)
  ivw_result <- matrix(ncol=4, nrow=25)


  for (seq in (1:25)) {
    seq_i_predictions = subset(seq_predictions, seq_num == seq)

    bxt <- unlist(seq_i_predictions["X_pred_mean"])
    bxset <- unlist(seq_i_predictions["X_pred_var"])
    byt <- unlist(seq_i_predictions["Y_pred_mean"])
    byset <- unlist(seq_i_predictions["Y_pred_var"])
    MRInputObject <- mr_input(bx = bxt,
                              bxse = bxset,
                              by = byt,
                              byse = byset)
    EggerObject <- mr_egger(MRInputObject)
    IVWObject <- mr_ivw(MRInputObject)

    egger_result[seq, ] <- c(
      EggerObject$Estimate,
      EggerObject$CILower.Est,
      EggerObject$CIUpper.Est,
      EggerObject$I.sq,
      EggerObject$Pleio.pval,
      EggerObject$StdError.Est
    )
    ivw_result[seq, ] <- c(IVWObject$Estimate, IVWObject$CILower, IVWObject$CIUpper, IVWObject$StdError)
  }

  colnames(egger_result) <- c("ce", "cil", "ciu", "i.sq", "pleio", "std")
  egger_result <- as_tibble(egger_result)
  meta_result <- meta::metagen(egger_result$ce, egger_result$std)
  
  p <- qplot(ce, data=egger_result, binwidth=.25)
  result[i, ] <- c(f, round(c(meta_result$TE.random, meta_result$seTE.random, meta_result$pval.random, meta_result$tau2), digits = 3))
}
```

```{r}
colnames(result) <- c("TF", "Mean", "Std", "$ p $", "$ \tau^2 $")
t <- as_tibble(result) %>%
  mutate(
    TF = sapply(str_split(TF, "_"), function(x) x[2])
  ) %>%
  kable("latex", escape = F) %>%
  kable_styling(c("striped", "bordered")) %>%
  add_header_above(c(" " = 1, "Treatment Effect" = 3, "Heterogeneity" = 1))
t
```

```{r}
for (i in 1:2) {
  f <- files[i]
  # print(f)
  #
  seq_predictions = read.csv(file.path("../../dat/res/", f))
  # # do.call(cbind, lapply(x, is.nan))

  seq_predictions[is.nan(seq_predictions)] <- 0
  seq_predictions <- seq_predictions %>%
    filter(
      X_pred_var > 0 & Y_pred_var > 0
    )

  ivw_vals = list()
  egger_vals = list()

  egger_result <- matrix(ncol=6, nrow=25)
  ivw_result <- matrix(ncol=4, nrow=25)


  for (seq in (1:25)) {
    seq_i_predictions = subset(seq_predictions, seq_num == seq)

    bxt <- unlist(seq_i_predictions["X_pred_mean"])
    bxset <- unlist(seq_i_predictions["X_pred_var"])
    byt <- unlist(seq_i_predictions["Y_pred_mean"])
    byset <- unlist(seq_i_predictions["Y_pred_var"])
    MRInputObject <- mr_input(bx = bxt,
                              bxse = bxset,
                              by = byt,
                              byse = byset)
    EggerObject <- mr_egger(MRInputObject)
    IVWObject <- mr_ivw(MRInputObject)

    egger_result[seq, ] <- c(
      EggerObject$Estimate,
      EggerObject$CILower.Est,
      EggerObject$CIUpper.Est,
      EggerObject$I.sq,
      EggerObject$Pleio.pval,
      EggerObject$StdError.Est
    )
    ivw_result[seq, ] <- c(IVWObject$Estimate, IVWObject$CILower, IVWObject$CIUpper, IVWObject$StdError)
  }

  colnames(egger_result) <- c("ce", "cil", "ciu", "i.sq", "pleio", "std")
  egger_result <- as_tibble(egger_result)
  meta_result <- meta::metagen(egger_result$ce, egger_result$std)
  
  p <- qplot(ce, data=egger_result, binwidth=.25)
  result[i, ] <- c(f, round(c(meta_result$TE.random, meta_result$seTE.random, meta_result$pval.random, meta_result$tau2), digits = 3))
}
```
```
