---
title: "Simulation Analysis"
author: "Stephen Malina"
date: "11/16/2020"
output: html_document
params:
  save_plots: TRUE
  recompute_meta: TRUE
  mr_method: "egger"
  alpha: .05
  seed: 42
---

```{r setup, include=FALSE}
library(MendelianRandomization)
library(dplyr)

library(ks)
library(stats)
library(meta)
library(mr.raps)
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(gridExtra)
library(stringr)
library(foreach)
library(purrr)
library(slider)
library(ks)
library(doSNOW)
library(sampler)
# library(reshape)
source("utils.R")
set.seed(params$seed)
```

## Functions
Here we define functions for running MR on our sequence-specific effect sizes
and standard errors and also for assessing the quality of the resulting
causal effects.

```{r}

```


```{r}
exp_tf <- "GATA"
out_tf <- "TAL1"

sim_results_dirs <- list(
  # Unconfounded
  "../../dat/sim_e2e_final/unconfounded/2021-05-29-01-24-49/",
  # Sequence-independent confounding
  "../../dat/sim_e2e_final/rand_confounded/res/2021-06-27-14-08-55/",
  # Sequence-dependent confounding
  "../../dat/sim_e2e_final/seq_confounded/res/2021-06-26-14-36-13/",
  # Both Confounder Types
  "../../dat/sim_e2e_final/confounded/2021-05-29-13-36-38/"
)

lapply(sim_results_dirs, function(sim_results_dir) {
  global_ces_list <- foreach(i=0:49) %do% {
    sim_eff_sizes_fname <- str_c(
      exp_tf, out_tf, "mr_inputs_calibrated.csv", sep="_"
    )
    seq_eff_sizes <-
      read.csv(file.path(sim_results_dir, str_c("round", sprintf("%d", i), sep="_"), sim_eff_sizes_fname)) %>%
      drop_na()
    n_seqs <- max(seq_eff_sizes$seq_num)
    mr_results <- run_mr(seq_eff_sizes, n_seqs, params$mr_method)
    mr_results <- mr_results %>% drop_na()
    naive_ces <- compute_baseline_ces(seq_eff_sizes, n_seqs)

    ce_key <- str_c(params$mr_method, "ce", sep=".")
    std_key <- str_c(params$mr_method, "std", sep=".")
    ci_keys <- paste(params$mr_method, c("ciu", "cil"), sep=".")
    if (params$mr_method != "raps") {
      cis <- mr_results[c(ci_keys, ce_key)] %>%
        rename("upper" = ci_keys[1], "lower" = ci_keys[2], "est" = ce_key)
    } else {
      cis <- data.frame(
        upper = mr_results$raps.ce + 2 * mr_results$raps.std,
        lower = mr_results$raps.ce - 2 * mr_results$raps.std
      )
    }
  
    sim_true_ces_fname <- str_c(exp_tf, out_tf, "true_ces.csv", sep="_")
    true_ces <- read.csv(file.path(sim_results_dir, str_c("round", sprintf("%d", i), sep="_"), sim_true_ces_fname))
    meta_result <- meta::metagen(get(ce_key, mr_results), get(std_key, mr_results), verbose=TRUE, digits=5, control=list(stepadj=0.5, maxiter=5000))
    naive_est <- mean(naive_ces)
    naive_est_upper <- mean(naive_ces) + 2 * sd(naive_ces)
    naive_est_lower <- mean(naive_ces) - 2 * sd(naive_ces)
    naive_mr_est <- mean(get(ce_key, mr_results))
  
    cis$true_val <- true_ces$CI[which(!is.na(cis$"upper"))]
    cis <- cis[!is.na(cis$true_val), ]
    calibration <- (measure_confidence_interval_calibration(cis))
    
    return(list(
      ce_est=meta_result$TE.random,
      ce_tau=meta_result$tau,
      ce_se=meta_result$seTE.random,
      ce_lower=meta_result$lower.random,
      ce_upper=meta_result$upper.random,
      true_ce_est=mean(true_ces$CI, na.rm = T),
      naive_est=naive_est,
      naive_mr_lower=naive_est_lower,
      naive_mr_upper=naive_est_upper,
      naive_mr_est=naive_mr_est,
      calibration=calibration
    ))
  }
  global_metrics <- as.data.frame(data.table::rbindlist(global_ces_list))
  output_dir <- file.path(sim_results_dir, "analysis")
  dir.create(output_dir, showWarnings = FALSE)
  output_fname <- str_c(exp_tf, out_tf, "global_metrics.csv", sep = "_")
  output_fpath <- file.path(output_dir, output_fname)
  write.table(global_metrics, output_fpath, row.names=FALSE, quote=FALSE)
})
```

```{r}
exp_tf <- "GATA"
out_tf <- "TAL1"

sim_results_dir <- "../../dat/sim_e2e_conf_strength/"
confounder_strengths <- seq(from=0, to=1, by=0.1)
sim_results_dirs <- 

lapply(confounder_strengths, function(confounder_strength) {
  sim_eff_sizes_fname <- str_c(
    exp_tf, out_tf, "mr_inputs_calibrated.csv", sep="_"
  )
  sim_results_dir <- file.path(
     "../../dat/sim_e2e_conf_strength/",
     sprintf("confounder_strength_exp_%0.1f"),
  )
  global_ces_list <- foreach(i=0:5) %do% {

    seq_eff_sizes <-
      read.csv(file.path(sim_results_dir, str_c("round", sprintf("%d", i), sep="_"), sim_eff_sizes_fname)) %>%
      drop_na()
    n_seqs <- max(seq_eff_sizes$seq_num)
    mr_results <- run_mr(seq_eff_sizes, n_seqs, params$mr_method)
    mr_results <- mr_results %>% drop_na()
    naive_ces <- compute_baseline_ces(seq_eff_sizes, n_seqs)

    ce_key <- str_c(params$mr_method, "ce", sep=".")
    std_key <- str_c(params$mr_method, "std", sep=".")
    ci_keys <- paste(params$mr_method, c("ciu", "cil"), sep=".")
    if (params$mr_method != "raps") {
      cis <- mr_results[c(ci_keys, ce_key)] %>%
        rename("upper" = ci_keys[1], "lower" = ci_keys[2], "est" = ce_key)
    } else {
      cis <- data.frame(
        upper = mr_results$raps.ce + 2 * mr_results$raps.std,
        lower = mr_results$raps.ce - 2 * mr_results$raps.std
      )
    }
  
    sim_true_ces_fname <- str_c(exp_tf, out_tf, "true_ces.csv", sep="_")
    true_ces <- read.csv(file.path(sim_results_dir, str_c("round", sprintf("%d", i), sep="_"), sim_true_ces_fname))
    meta_result <- meta::metagen(get(ce_key, mr_results), get(std_key, mr_results), verbose=TRUE, digits=5, control=list(stepadj=0.5, maxiter=5000))
    naive_est <- mean(naive_ces)
    naive_est_upper <- mean(naive_ces) + 2 * sd(naive_ces)
    naive_est_lower <- mean(naive_ces) - 2 * sd(naive_ces)
    naive_mr_est <- mean(get(ce_key, mr_results))
  
    cis$true_val <- true_ces$CI[which(!is.na(cis$"upper"))]
    cis <- cis[!is.na(cis$true_val), ]
    calibration <- (measure_confidence_interval_calibration(cis))
    
    return(list(
      ce_est=meta_result$TE.random,
      ce_tau=meta_result$tau,
      ce_se=meta_result$seTE.random,
      ce_lower=meta_result$lower.random,
      ce_upper=meta_result$upper.random,
      true_ce_est=mean(true_ces$CI, na.rm = T),
      naive_est=naive_est,
      naive_mr_lower=naive_est_lower,
      naive_mr_upper=naive_est_upper,
      naive_mr_est=naive_mr_est,
      calibration=calibration
    ))
  }
  global_metrics <- as.data.frame(data.table::rbindlist(global_ces_list))
  output_dir <- file.path(sim_results_dir, "analysis")
  dir.create(output_dir, showWarnings = FALSE)
  output_fname <- str_c(exp_tf, out_tf, "global_metrics.csv", sep = "_")
  output_fpath <- file.path(output_dir, output_fname)
  write.table(global_metrics, output_fpath, row.names=FALSE, quote=FALSE)
})
```

