---
title: "Mendelian Randomization analysis of DeepSEA generated data"
output: html_notebook
---
```{r}
library(MendelianRandomization)
```

```{r}
data_dir = "../../dat"
seq_predictions_all = read.csv(file.path(data_dir, "means_and_uncertainties_hopefully_correct.csv"))
seq_predictions = subset(seq_predictions_all, seq_num == 25)
```

```{r}
str(seq_predictions)
```
```{r}
bx <- unlist(seq_predictions["X_pred_mean"])
bxse <- unlist(seq_predictions["X_pred_var"])
by <- unlist(seq_predictions["Y_pred_mean"])
byse <- unlist(seq_predictions["Y_pred_var"])
```

```{r}
MRInputObjectEx <- mr_input(bx = bx, 
                          bxse = bxse, 
                          by = by, 
                          byse = byse)
```


```{r}
# cis = c()
# for (seq in (1:50)) {
#   seq_predictions = subset(seq_predictions_all, seq_num == seq)
#   
#   bxt <- unlist(seq_predictions["X_pred_mean"])
#   bxset <- unlist(seq_predictions["X_pred_var"])
#   byt <- unlist(seq_predictions["Y_pred_mean"])
#   byset <- unlist(seq_predictions["Y_pred_var"])
#   MRInputObject <- mr_input(bx = bxt, 
#                           bxse = bxset, 
#                           by = byt, 
#                           byse = byset)
#   EggerObject <- mr_egger(MRInputObject, robust = FALSE, alpha = .05)
#   # cis = append(cis, c(EggerObject$CILower.Est, EggerObject$CIUpper.Est))
#   print(seq)
#   print(c(EggerObject$CILower.Est, EggerObject$CIUpper.Est))
#   print(c(EggerObject$I.sq))
# }
# dim(cis) <- c(2, 50)
# print(cis)
```


```{r}
mr_plot(MRInputObjectEx)
```
```{r}
install.packages("devtools")
```

```{r}
library(devtools)
install_github("WSpiller/RadialMR")
```
```{r}
plot(by/bx, bx/byse, xlim=c(min((by-2*byse)/bx), max((bx+2*byse)/bx)), ylim=c(0, max(bx/byse)))
for (j in 1:length(bx)) {
lines(c((by[j]-1.96*byse[j])/bx[j], (by[j]+1.96*byse[j])/bx[j]),
c(bx[j]/byse[j], bx[j]/byse[j]))
}
abline(h=0, lwd=1); abline(v=0, lwd=1)
```
```{r}
library(RadialMR)
r_input <- format_radial(bx, by, bxse, byse)
funnel_radial(egger_radial(r_input, alpha = .05))
```

```{r}
plot_radial(ivw_radial(r_input, alpha = .05))
```

```{r}
plot_radial(egger_radial(r_input, alpha = .05))
```
